services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: loan-backend

    ports:
      - "8000:8000"


    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: loan-frontend

    ports:
      - "8501:8501"

    depends_on:
      - backend

    environment:
      API_BASE_URL: http://backend:8000

    restart: unless-stopped